# SPDX-License-Identifier: GPL-3.0-or-later

version: 2
updates:

  # Check for updates to GitHub Actions every month
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
